"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "yarn install --frozen-lockfile --non-interactive"
run_mode = "concurrent"

[scripts.run.dev]
command = "yarn start --port $CONDUCTOR_PORT"
available_in = [ "local" ]
default = true
icon = "play"
